---
name: release

on: # yamllint disable rule:truthy
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${TAG%%-*}" >> ${GITHUB_ENV}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=docs/release-notes/${{env.RELEASE_VERSION}}.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
